// Generated by Dagger (https://dagger.dev).
package ahmed.atwa.popularmovies.detail;

import ahmed.atwa.popularmovies.movies.data.MovieRepo;
import ahmed.atwa.popularmovies.config.commons.CoroutineDispatcher;
import ahmed.atwa.popularmovies.detail.presentation.DetailViewModel;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class DetailViewModel_Factory implements Factory<DetailViewModel> {
  private final Provider<MovieRepo> movieRepoProvider;

  private final Provider<CoroutineDispatcher> dispatcherProvider;

  public DetailViewModel_Factory(Provider<MovieRepo> movieRepoProvider,
      Provider<CoroutineDispatcher> dispatcherProvider) {
    this.movieRepoProvider = movieRepoProvider;
    this.dispatcherProvider = dispatcherProvider;
  }

  @Override
  public DetailViewModel get() {
    return new DetailViewModel(movieRepoProvider.get(), dispatcherProvider.get());
  }

  public static DetailViewModel_Factory create(Provider<MovieRepo> movieRepoProvider,
      Provider<CoroutineDispatcher> dispatcherProvider) {
    return new DetailViewModel_Factory(movieRepoProvider, dispatcherProvider);
  }

  public static DetailViewModel newInstance(MovieRepo movieRepo, CoroutineDispatcher dispatcher) {
    return new DetailViewModel(movieRepo, dispatcher);
  }
}
