// Generated by Dagger (https://dagger.dev).
package ahmed.atwa.popularmovies.detail;

import androidx.lifecycle.ViewModelProvider;
import androidx.recyclerview.widget.LinearLayoutManager;

import ahmed.atwa.popularmovies.detail.presentation.DetailFragment;
import ahmed.atwa.popularmovies.detail.presentation.TrailerAdapter;
import dagger.MembersInjector;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class DetailFragment_MembersInjector implements MembersInjector<DetailFragment> {
  private final Provider<ViewModelProvider.Factory> mViewModelFactoryProvider;

  private final Provider<LinearLayoutManager> mLinearLayoutManagerProvider;

  private final Provider<TrailerAdapter> mTrailerAdapterProvider;

  public DetailFragment_MembersInjector(
      Provider<ViewModelProvider.Factory> mViewModelFactoryProvider,
      Provider<LinearLayoutManager> mLinearLayoutManagerProvider,
      Provider<TrailerAdapter> mTrailerAdapterProvider) {
    this.mViewModelFactoryProvider = mViewModelFactoryProvider;
    this.mLinearLayoutManagerProvider = mLinearLayoutManagerProvider;
    this.mTrailerAdapterProvider = mTrailerAdapterProvider;
  }

  public static MembersInjector<DetailFragment> create(
      Provider<ViewModelProvider.Factory> mViewModelFactoryProvider,
      Provider<LinearLayoutManager> mLinearLayoutManagerProvider,
      Provider<TrailerAdapter> mTrailerAdapterProvider) {
    return new DetailFragment_MembersInjector(mViewModelFactoryProvider, mLinearLayoutManagerProvider, mTrailerAdapterProvider);}

  @Override
  public void injectMembers(DetailFragment instance) {
    injectMViewModelFactory(instance, mViewModelFactoryProvider.get());
    injectMLinearLayoutManager(instance, mLinearLayoutManagerProvider.get());
    injectMTrailerAdapter(instance, mTrailerAdapterProvider.get());
  }

  public static void injectMViewModelFactory(DetailFragment instance,
      ViewModelProvider.Factory mViewModelFactory) {
    instance.mViewModelFactory = mViewModelFactory;
  }

  public static void injectMLinearLayoutManager(DetailFragment instance,
      LinearLayoutManager mLinearLayoutManager) {
    instance.mLinearLayoutManager = mLinearLayoutManager;
  }

  public static void injectMTrailerAdapter(DetailFragment instance,
      TrailerAdapter mTrailerAdapter) {
    instance.mTrailerAdapter = mTrailerAdapter;
  }
}
