// Generated by Dagger (https://dagger.dev).
package ahmed.atwa.popularmovies.main;

import androidx.fragment.app.Fragment;

import ahmed.atwa.popularmovies.main.presentation.MainActivity;
import ahmed.atwa.popularmovies.main.presentation.MainViewModel;
import dagger.MembersInjector;
import dagger.android.DispatchingAndroidInjector;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class MainActivity_MembersInjector implements MembersInjector<MainActivity> {
  private final Provider<DispatchingAndroidInjector<Fragment>> fragmentDispatchingAndroidInjectorProvider;

  private final Provider<MainViewModel> mMainViewModelProvider;

  public MainActivity_MembersInjector(
      Provider<DispatchingAndroidInjector<Fragment>> fragmentDispatchingAndroidInjectorProvider,
      Provider<MainViewModel> mMainViewModelProvider) {
    this.fragmentDispatchingAndroidInjectorProvider = fragmentDispatchingAndroidInjectorProvider;
    this.mMainViewModelProvider = mMainViewModelProvider;
  }

  public static MembersInjector<MainActivity> create(
      Provider<DispatchingAndroidInjector<Fragment>> fragmentDispatchingAndroidInjectorProvider,
      Provider<MainViewModel> mMainViewModelProvider) {
    return new MainActivity_MembersInjector(fragmentDispatchingAndroidInjectorProvider, mMainViewModelProvider);}

  @Override
  public void injectMembers(MainActivity instance) {
    injectFragmentDispatchingAndroidInjector(instance, fragmentDispatchingAndroidInjectorProvider.get());
    injectMMainViewModel(instance, mMainViewModelProvider.get());
  }

  public static void injectFragmentDispatchingAndroidInjector(MainActivity instance,
      DispatchingAndroidInjector<Fragment> fragmentDispatchingAndroidInjector) {
    instance.fragmentDispatchingAndroidInjector = fragmentDispatchingAndroidInjector;
  }

  public static void injectMMainViewModel(MainActivity instance, MainViewModel mMainViewModel) {
    instance.mMainViewModel = mMainViewModel;
  }
}
