// Generated by Dagger (https://dagger.dev).
package ahmed.atwa.popularmovies.main;

import ahmed.atwa.popularmovies.main.presentation.MainViewModel;
import ahmed.atwa.popularmovies.movies.data.MovieRepoImp;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class MainViewModel_Factory implements Factory<MainViewModel> {
  private final Provider<MovieRepoImp> movieRepositoryProvider;

  public MainViewModel_Factory(Provider<MovieRepoImp> movieRepositoryProvider) {
    this.movieRepositoryProvider = movieRepositoryProvider;
  }

  @Override
  public MainViewModel get() {
    return new MainViewModel(movieRepositoryProvider.get());
  }

  public static MainViewModel_Factory create(Provider<MovieRepoImp> movieRepositoryProvider) {
    return new MainViewModel_Factory(movieRepositoryProvider);
  }

  public static MainViewModel newInstance(MovieRepoImp movieRepository) {
    return new MainViewModel(movieRepository);
  }
}
