// Generated by Dagger (https://dagger.dev).
package ahmed.atwa.popularmovies.movies;

import ahmed.atwa.popularmovies.movies.domain.MovieEntity;
import android.content.Context;

import ahmed.atwa.popularmovies.movies.presentation.MovieAdapter;
import dagger.internal.Factory;
import java.util.List;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class MovieAdapter_Factory implements Factory<MovieAdapter> {
  private final Provider<List<MovieEntity>> mMoviesListProvider;

  private final Provider<Context> mContextProvider;

  public MovieAdapter_Factory(Provider<List<MovieEntity>> mMoviesListProvider,
      Provider<Context> mContextProvider) {
    this.mMoviesListProvider = mMoviesListProvider;
    this.mContextProvider = mContextProvider;
  }

  @Override
  public MovieAdapter get() {
    return new MovieAdapter(mMoviesListProvider.get(), mContextProvider.get());
  }

  public static MovieAdapter_Factory create(Provider<List<MovieEntity>> mMoviesListProvider,
      Provider<Context> mContextProvider) {
    return new MovieAdapter_Factory(mMoviesListProvider, mContextProvider);
  }

  public static MovieAdapter newInstance(List<MovieEntity> mMoviesList, Context mContext) {
    return new MovieAdapter(mMoviesList, mContext);
  }
}
