// Generated by Dagger (https://dagger.dev).
package ahmed.atwa.popularmovies.movies;

import ahmed.atwa.popularmovies.config.commons.GridSpacingItemDecoration;
import androidx.lifecycle.ViewModelProvider;
import androidx.recyclerview.widget.GridLayoutManager;

import ahmed.atwa.popularmovies.movies.presentation.MovieAdapter;
import ahmed.atwa.popularmovies.movies.presentation.MoviesFragment;
import dagger.MembersInjector;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class MoviesFragment_MembersInjector implements MembersInjector<MoviesFragment> {
  private final Provider<ViewModelProvider.Factory> mViewModelFactoryProvider;

  private final Provider<GridLayoutManager> mGridLayoutManagerProvider;

  private final Provider<GridSpacingItemDecoration> mGridSpacingItemDecorationProvider;

  private final Provider<MovieAdapter> mMovieAdapterProvider;

  public MoviesFragment_MembersInjector(
      Provider<ViewModelProvider.Factory> mViewModelFactoryProvider,
      Provider<GridLayoutManager> mGridLayoutManagerProvider,
      Provider<GridSpacingItemDecoration> mGridSpacingItemDecorationProvider,
      Provider<MovieAdapter> mMovieAdapterProvider) {
    this.mViewModelFactoryProvider = mViewModelFactoryProvider;
    this.mGridLayoutManagerProvider = mGridLayoutManagerProvider;
    this.mGridSpacingItemDecorationProvider = mGridSpacingItemDecorationProvider;
    this.mMovieAdapterProvider = mMovieAdapterProvider;
  }

  public static MembersInjector<MoviesFragment> create(
      Provider<ViewModelProvider.Factory> mViewModelFactoryProvider,
      Provider<GridLayoutManager> mGridLayoutManagerProvider,
      Provider<GridSpacingItemDecoration> mGridSpacingItemDecorationProvider,
      Provider<MovieAdapter> mMovieAdapterProvider) {
    return new MoviesFragment_MembersInjector(mViewModelFactoryProvider, mGridLayoutManagerProvider, mGridSpacingItemDecorationProvider, mMovieAdapterProvider);}

  @Override
  public void injectMembers(MoviesFragment instance) {
    injectMViewModelFactory(instance, mViewModelFactoryProvider.get());
    injectMGridLayoutManager(instance, mGridLayoutManagerProvider.get());
    injectMGridSpacingItemDecoration(instance, mGridSpacingItemDecorationProvider.get());
    injectMMovieAdapter(instance, mMovieAdapterProvider.get());
  }

  public static void injectMViewModelFactory(MoviesFragment instance,
      ViewModelProvider.Factory mViewModelFactory) {
    instance.mViewModelFactory = mViewModelFactory;
  }

  public static void injectMGridLayoutManager(MoviesFragment instance,
      GridLayoutManager mGridLayoutManager) {
    instance.mGridLayoutManager = mGridLayoutManager;
  }

  public static void injectMGridSpacingItemDecoration(MoviesFragment instance,
      GridSpacingItemDecoration mGridSpacingItemDecoration) {
    instance.mGridSpacingItemDecoration = mGridSpacingItemDecoration;
  }

  public static void injectMMovieAdapter(MoviesFragment instance, MovieAdapter mMovieAdapter) {
    instance.mMovieAdapter = mMovieAdapter;
  }
}
