// Generated by Dagger (https://dagger.dev).
package ahmed.atwa.popularmovies.movies;

import ahmed.atwa.popularmovies.movies.data.MovieRepo;
import ahmed.atwa.popularmovies.config.commons.CoroutineDispatcher;
import ahmed.atwa.popularmovies.movies.presentation.MoviesViewModel;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class MoviesViewModel_Factory implements Factory<MoviesViewModel> {
  private final Provider<MovieRepo> movieRepoProvider;

  private final Provider<CoroutineDispatcher> dispatcherProvider;

  public MoviesViewModel_Factory(Provider<MovieRepo> movieRepoProvider,
      Provider<CoroutineDispatcher> dispatcherProvider) {
    this.movieRepoProvider = movieRepoProvider;
    this.dispatcherProvider = dispatcherProvider;
  }

  @Override
  public MoviesViewModel get() {
    return new MoviesViewModel(movieRepoProvider.get(), dispatcherProvider.get());
  }

  public static MoviesViewModel_Factory create(Provider<MovieRepo> movieRepoProvider,
      Provider<CoroutineDispatcher> dispatcherProvider) {
    return new MoviesViewModel_Factory(movieRepoProvider, dispatcherProvider);
  }

  public static MoviesViewModel newInstance(MovieRepo movieRepo, CoroutineDispatcher dispatcher) {
    return new MoviesViewModel(movieRepo, dispatcher);
  }
}
